"""first database with Artist, Event, Venue, ArtistToEvent

Revision ID: 32976119a128
Revises: 
Create Date: 2019-10-14 11:12:40.322250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32976119a128'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('hometown', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Artist_hometown'), 'Artist', ['hometown'], unique=False)
    op.create_index(op.f('ix_Artist_name'), 'Artist', ['name'], unique=True)
    op.create_table('Venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Venue_address'), 'Venue', ['address'], unique=False)
    op.create_index(op.f('ix_Venue_name'), 'Venue', ['name'], unique=True)
    op.create_table('Event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('venueID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['venueID'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Event_date'), 'Event', ['date'], unique=False)
    op.create_index(op.f('ix_Event_title'), 'Event', ['title'], unique=False)
    op.create_table('ArtistToEvent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventID', sa.Integer(), nullable=True),
    sa.Column('artistID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artistID'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['eventID'], ['Event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ArtistToEvent')
    op.drop_index(op.f('ix_Event_title'), table_name='Event')
    op.drop_index(op.f('ix_Event_date'), table_name='Event')
    op.drop_table('Event')
    op.drop_index(op.f('ix_Venue_name'), table_name='Venue')
    op.drop_index(op.f('ix_Venue_address'), table_name='Venue')
    op.drop_table('Venue')
    op.drop_index(op.f('ix_Artist_name'), table_name='Artist')
    op.drop_index(op.f('ix_Artist_hometown'), table_name='Artist')
    op.drop_table('Artist')
    # ### end Alembic commands ###
